pipeline {
    agent any

    environment {
		DOCKERHUB_CREDENTIALS=credentials('dockerhub')
	}
    stages {
        stage('Docker Login') {
            steps {
              sh 'echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin'
            }
        }
        stage('Build & push Dockerfile') {
            steps {
              sh """
              cd comingsoon/
              ansible-playbook playbook.yml
              """
            }
        }
        stage('Create Cluster') {
            steps {
                  sh """
                  minikube start create cluster comingsoon-cluster --nodes=2
                  """
                }
            }
        stage('Create Namespace') {
            steps {
                  sh "kubectl create namespace jenkins"
                }
            }
        stage('Deploy') {
            steps {
                  sh """
                  cd comingsoon/k8s
                  kubectl -n comingsoon apply -f deployment.yaml
                  kubectl -n comingsoon apply -f services.yaml
                  """
                }
            }
        }
    }
