apiVersion: apps/v1
kind: Deployment
metadata:
  name: comingsoon-page-img-deployment
  namespace: default
spec:
  selector:
    matchLabels:
      app: comingsoon-page
  replicas: 2
  template:
    metadata:
      labels:
        app: comingsoon-page
    spec:
      containers:
      - name: comingsoon-page
        image: imas10/devopssite2
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: comingsoon-page
  namespace: default
spec:
  selector:
    app: comingsoon-page
  # ClusterIP (default), LoadBalancer (works on cloud), NodePort (most used)
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
