apiVersion: v1
kind: Service
metadata:
  name: comingsoon-page
  namespace: jenkins
spec:
  selector:
    app: comingsoon-page
# ClusterIP (default), LoadBalancer (works on cloud), NodePort (most used)
  type: NodePort
  ports:
  - protocol: TCP
    port: 80 
    targetPort: 80 
